import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import { createApp } from './app.js';
async function withServer(options,fn){const server=createApp(options).listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));try{await fn(`http://127.0.0.1:${server.address().port}`);}finally{await new Promise(resolve=>server.close(resolve));}}
async function imageForm(){const buffer=await sharp({create:{width:16,height:16,channels:3,background:'#12372a'}}).png().toBuffer();const body=new FormData();body.append('image',new Blob([buffer],{type:'image/png'}),'leaf.png');return body;}
test('backend reports missing setup without internal configuration details',async()=>{await withServer({apiKey:''},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,503);assert.match((await r.json()).error,/não está configurado/);});});
test('rejects corrupt images without calling provider',async()=>{await withServer({apiKey:'test-only',request:()=>{throw new Error('must not call');}},async base=>{const body=new FormData();body.append('image',new Blob(['not an image'],{type:'image/png'}),'bad.png');const r=await fetch(`${base}/api/analyze`,{method:'POST',body});assert.equal(r.status,400);});});
test('workflow payload and empty detection result; key only in server-side payload',async()=>{await withServer({apiKey:'test-only-secret',request:async(url,options)=>{assert.match(url,/doencas-o41wy$/);const body=JSON.parse(options.body);assert.equal(options.headers.Authorization,undefined);assert.equal(body.api_key,'test-only-secret');assert.equal(body.inputs.classes,undefined);assert.equal(body.inputs.image.type,'base64');assert.deepEqual(Object.keys(body.inputs),['image']);return Response.json({outputs:[{predictions:{predictions:[]}}]});}},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,200);const data=await r.json();assert.deepEqual(data.detections,[]);assert.match(data.originalImage,/^data:image\/jpeg;base64,/);assert.equal(JSON.stringify(data).includes('test-only-secret'),false);});});
test('upstream failures do not expose sensitive provider messages',async()=>{await withServer({apiKey:'test-only',request:async()=>new Response('secret provider details',{status:401})},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,502);assert.equal((await r.text()).includes('secret provider'),false);});});
for(const status of [401,403,429,500]) test(`provider status ${status} is mapped safely`,async()=>{await withServer({apiKey:'test-only',request:async()=>new Response('private upstream message',{status})},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,status===429?429:502);const data=await r.json();assert.equal(data.error.includes('private upstream'),false);if([401,403].includes(status))assert.match(data.error,/autenticar/);});});
test('provider timeout has actionable safe message',async()=>{await withServer({apiKey:'test-only',request:async()=>{throw new DOMException('private details','TimeoutError');}},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,504);assert.match((await r.json()).error,/demorou/);});});
test('unsupported provider output is not presented as no detections',async()=>{await withServer({apiKey:'test-only',request:async()=>Response.json({outputs:[{}]})},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,502);assert.match((await r.json()).error,/incompatível/);});});


test('network failures never expose credentials',async()=>{await withServer({apiKey:'test-only-secret',request:async()=>{throw new TypeError('network test-only-secret');}},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,502);assert.equal((await r.text()).includes('test-only-secret'),false);});});

test('backend delivers returned segmentation and confidence to frontend',async()=>{await withServer({apiKey:'test-only',request:async()=>Response.json({outputs:[{predictions:{image:{width:16,height:16},predictions:[{class:'phomarotation',confidence:0.82,points:[{x:1,y:1},{x:8,y:1},{x:8,y:8}]}]}}]})},async base=>{const r=await fetch(`${base}/api/analyze`,{method:'POST',body:await imageForm()});assert.equal(r.status,200);const data=await r.json();assert.equal(data.detections[0].className,'phomarotation');assert.equal(data.detections[0].confidence,0.82);assert.equal(data.detections[0].points.length,3);});});
