import { useCallback, useEffect, useRef, useState } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { Camera, Leaf, ShieldCheck, ArrowUpRight, Focus, Sun, Sprout, ScanLine, Bug, CircleHelp, X } from 'lucide-react';
import { Header, Logo } from './components/Header';
import { ImageUpload } from './components/ImageUpload';
import { ImagePreview } from './components/ImagePreview';
import { AnalysisButton } from './components/AnalysisButton';
import { LoadingAnalysis } from './components/LoadingAnalysis';
import { CameraCapture } from './components/CameraCapture';
import { AnalysisResults } from './components/AnalysisResults';
import { prepareImage } from './services/image';
import { analyzeImage } from './services/analysis';
import type { Analysis } from './types';
import { classStyles } from './config/classes';
const diseases=[{name:'Bicho-mineiro',kind:'PRAGA',detail:'Monitoramento de possíveis lesões causadas pelo bicho-mineiro.',icon:Bug},{name:'Cercosporiose',kind:'DOENÇA',detail:'Identificação de regiões compatíveis com cercosporiose.',icon:Focus},{name:'Ferrugem do cafeeiro',kind:'DOENÇA',detail:'Análise de possíveis sinais de ferrugem nas folhas.',icon:Leaf},{name:'Mancha de Phoma',kind:'DOENÇA',detail:'Detecção de possíveis regiões afetadas pela mancha de Phoma.',icon:Sprout}];
export default function App(){
 const [file,setFile]=useState<File|null>(null);const [url,setUrl]=useState('');const [camera,setCamera]=useState(false);const [busy,setBusy]=useState(false);const [preparing,setPreparing]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Analysis|null>(null);const controller=useRef<AbortController|null>(null);const selecting=useRef(false);const analyzing=useRef(false);const mounted=useRef(true);const reduce=useReducedMotion();
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);
 useEffect(()=>{if(!file){setUrl('');return;}const objectURL=URL.createObjectURL(file);setUrl(objectURL);return()=>URL.revokeObjectURL(objectURL);},[file]);
 const closeCamera=useCallback(()=>setCamera(false),[]);
 async function select(image:File){if(selecting.current||analyzing.current)return;selecting.current=true;setPreparing(true);setError('');try{const prepared=await prepareImage(image);if(mounted.current){setFile(prepared);setResult(null);}}catch(e){if(mounted.current)setError((e as Error).message);}finally{selecting.current=false;if(mounted.current)setPreparing(false);}}
 async function analyze(){if(!file||analyzing.current)return;analyzing.current=true;setBusy(true);setError('');controller.current=new AbortController();try{const data=await analyzeImage(file,controller.current.signal);if(mounted.current)setResult(data);}catch(e){if(mounted.current)setError((e as Error).name==='TimeoutError'?'A análise demorou mais que o esperado. Tente novamente.':(e as Error).name==='TypeError'?'Não foi possível conectar ao servidor. Verifique a conexão e tente novamente.':(e as Error).message);}finally{analyzing.current=false;if(mounted.current)setBusy(false);}}
 function reset(){setResult(null);setFile(null);setError('');}
 return <><Header/><main><motion.section className="hero" initial={reduce?false:{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{duration:0.6}}><span className="hero-label"><span/> TECNOLOGIA QUE CUIDA DO SEU CAFÉ</span><h1>Identifique pragas e doenças<br className="desktop-break"/> do café com <span>Inteligência Artificial<svg viewBox="0 0 500 15" preserveAspectRatio="none" aria-hidden="true"><path d="M2 11 Q240 -4 498 8"/></svg></span></h1><p>Capture uma imagem ou envie uma foto da folha de café<br className="desktop-break"/> para realizar uma análise inteligente.</p><div className="hero-benefits"><span><ScanLine size={16}/>Análise por imagem</span><span className="benefit-dot">·</span><span><ShieldCheck size={16}/>Suas imagens não são armazenadas</span></div></motion.section>
 <section id="analisar" className="workspace"><div className="analysis-panel">{result?<AnalysisResults result={result} onReset={reset}/>:<><div className="panel-heading"><span className="section-icon"><ScanLine size={21}/></span><div><h2>Um olhar inteligente para sua lavoura</h2><p>Escolha como deseja começar a análise.</p></div><span className="step-tag">PASSO 01 / 02</span></div>{file&&url?<ImagePreview url={url} disabled={busy||preparing} onRemove={()=>setFile(null)}/>:<ImageUpload onSelect={select} disabled={busy||preparing}/>}<div className="or-divider"><span>ou utilize a câmera</span></div><button className="button camera-button" disabled={busy||preparing} onClick={()=>{setError('');setCamera(true);}}><Camera size={21}/>{file?'Capturar novamente':'Abrir câmera'}<ArrowUpRight size={17}/></button><p className="camera-caption">Capture uma foto diretamente do seu celular ou computador.</p><div className="analysis-bottom"><AnalysisButton disabled={!file||preparing} loading={busy} onClick={analyze}/>{busy?<LoadingAnalysis/>:<small>{preparing?'Preparando sua imagem…':file?'Tudo pronto. Inicie a análise da folha.':'Selecione ou capture uma imagem para continuar.'}</small>}</div></>}{error&&<div className="error" role="alert"><CircleHelp size={20}/><span>{error}</span><button className="icon-button" aria-label="Fechar mensagem" onClick={()=>setError('')}><X size={18}/></button></div>}</div><aside className="tips"><div className="tips-art"><div className="leaf-orbit orbit-one"/><div className="leaf-orbit orbit-two"/><Leaf size={70} strokeWidth={1}/><span className="scan-corner top-left"/><span className="scan-corner bottom-right"/><span className="art-label"><span/> VISÃO COMPUTACIONAL</span></div><span className="eyebrow">UMA BOA FOTO FAZ A DIFERENÇA</span><h2>Mais nitidez.<br/>Melhor análise.</h2><p>Pequenos cuidados ajudam a IA a identificar os sinais na sua folha.</p><ul><li><Sun size={20}/><div><strong>Prefira luz natural</strong><span>Evite sombras e reflexos intensos.</span></div></li><li><Focus size={20}/><div><strong>Aproxime e mantenha o foco</strong><span>Os detalhes da folha devem estar nítidos.</span></div></li><li><Leaf size={20}/><div><strong>Uma folha por vez</strong><span>Use um fundo simples e enquadre a folha.</span></div></li></ul><div className="tips-note"><ShieldCheck size={19}/><span>A imagem é usada apenas para esta análise e não é salva pela aplicação.</span></div></aside></section>
 <section id="como-funciona" className="how-section"><div className="section-title"><span className="eyebrow">DO CAMPO À INFORMAÇÃO</span><h2>Simples em cada etapa.</h2><p>Um novo aliado no cuidado com o seu café.</p></div><div className="steps">{[{title:'Capture ou envie',text:'Escolha uma foto nítida de uma folha de café.',icon:Camera},{title:'Deixe a IA analisar',text:'A visão computacional busca possíveis sinais na imagem.',icon:ScanLine},{title:'Conheça os resultados',text:'Veja as ocorrências e as regiões identificadas.',icon:Sprout}].map((step,i)=><div className="step" key={step.title}><span className="step-number">0{i+1}</span><step.icon size={25}/><h3>{step.title}</h3><p>{step.text}</p></div>)}</div></section>
 <section id="o-que-identificamos" className="diseases-section"><div className="section-title"><span className="eyebrow">O QUE IDENTIFICAMOS</span><h2>Atenção aos sinais da sua lavoura.</h2><p>Análise direcionada a quatro possíveis ocorrências nas folhas de café.</p></div><div className="disease-grid">{diseases.map(d=><article key={d.name} style={{color: Object.values(classStyles).find(c=>c.name===d.name)?.color}}><div><span className="disease-icon" style={{color: Object.values(classStyles).find(c=>c.name===d.name)?.color}}><d.icon size={23}/></span><span className="disease-kind">{d.kind}</span></div><h3>{d.name}</h3><p>{d.detail}</p></article>)}</div><div className="disclaimer"><CircleHelp size={18}/><p>Uma ferramenta de apoio à observação. As estimativas da IA não substituem uma avaliação técnica agronômica.</p></div></section></main><footer><Logo/><span>Inteligência no campo. Cuidado em cada folha.</span><small>PragaCaféIA © {new Date().getFullYear()}</small></footer>{camera&&<CameraCapture onCapture={select} onClose={closeCamera}/>}</>;
}

